development:
  adapter: mysql2
  encoding: utf8
  database: api_analytics
  host: localhost
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  database: api_analytics
  host: gorgeous-dry-tortugas-96522
  username: root
  password: root