development:
  adapter: mysql2
  encoding: utf8
  database: api_analytics
  host: localhost
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  database: api_analytics
  host: 172.19.11.194
  username: root
  password: root