development:
  adapter: mysql2
  encoding: utf8
  database: api_analytics
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: api_analytics
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  socket: /var/lib/mysql/mysql.sock

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: mysql2
  encoding: utf8
  database: api_analytics
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  socket: /var/lib/mysql/mysql.sock